alias: Daytime Cheap 8-20
description: Turn on helper during the cheapest 4 hours in daytime window (8am-8pm)
triggers:
  - trigger: state
    entity_id: input_number.electricity_price_rank_daytime
  - trigger: time_pattern
    minutes: "/15"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {% set rank = states('input_number.electricity_price_rank_daytime') | int(99) %}
              {{ rank < 4 }}
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.daytime_cheap_7_21
    default:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.daytime_cheap_7_21
mode: single

