alias: Hot water temperature
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.manifoldtemperature_hot_water_boiler_temp
    for:
      hours: 0
      minutes: 0
      seconds: 10
    below: 20
    above: 5
  - trigger: numeric_state
    entity_id:
      - sensor.manifoldtemperature_hot_water_boiler_temp
    for:
      hours: 0
      minutes: 0
      seconds: 10
    above: 32
conditions: []
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.manifoldtemperature_hot_water_boiler_temp
        above: 30
    then:
      - action: input_boolean.turn_off
        metadata: {}
        target:
          entity_id: input_boolean.hot_water_notified
        data: {}
    else:
      - if:
          - condition: state
            entity_id: input_boolean.hot_water_notified
            state:
              - "off"
        then:
          - action: input_boolean.turn_on
            metadata: {}
            target:
              entity_id: input_boolean.hot_water_notified
            data: {}
          - action: notify.persistent_notification
            metadata: {}
            data:
              message: "Hot water, isn't. Alarm: 1"
              data:
                tag: hot_water
                uri: /dashboard-dash/boiler
          - device_id: 911ce9be1f83a09b179821cb2c9c0de6
            domain: mobile_app
            type: notify
            message: Hot water, isn't.
mode: single
